window.IDENTITY_DATA = {
  pools: {
    GOD: [
      { t: "自摸神手", q: "唔好意思呀，我又自摸喇，你哋快啲比錢啦。", c: "bg-indigo-100 text-indigo-700", tags: ["shark", "hot"] },
      { t: "中環雀王", q: "今晚全場我買單，邊個都唔准同我爭。", c: "bg-amber-100 text-amber-700", tags: ["grinder", "steady"] },
      { t: "至尊雀聖", q: "你同我鬥，不如直接將銀包遞畀我啦。", c: "bg-yellow-100 text-yellow-700", tags: ["shark", "steady"] },
      { t: "冷面雀神", q: "牌局如戰場，我唔會對任何人心軟。", c: "bg-slate-800 text-white", tags: ["shark", "observer"] },
      { t: "傳奇十三么", q: "大牌唔係你想做就有，係要天意配合。", c: "bg-purple-100 text-purple-700", tags: ["explosive", "hot"] },
      { t: "不敗神話", q: "求一敗而不可得，寂寞係我嘅代稱。", c: "bg-yellow-500 text-white", tags: ["shark", "grinder"] },
      { t: "雀界攞命陳", q: "我唔係針對邊個，我係話在座各位都係畀錢我使。", c: "bg-red-600 text-white", tags: ["hot", "explosive"] },
      { t: "通殺大將軍", q: "一家贏三家，你哋啲錢我幫你儲埋先。", c: "bg-orange-600 text-white", tags: ["hot", "grinder"] },
      { t: "贏到驚星人", q: "贏到我自己都唔好意思，下次再贏過。", c: "bg-pink-600 text-white", tags: ["steady", "grinder"] },
      { t: "無敵破壞王", q: "我一坐低，呢張檯就注定要爆。", c: "bg-rose-700 text-white", tags: ["explosive", "chaos"] },
      { t: "一哥收數佬", q: "今晚我唔係嚟打牌，我係嚟收數。", c: "bg-emerald-700 text-white", tags: ["grinder", "shark"] },
      { t: "封盤大魔王", q: "你哋仲未開始追，我已經收咗工。", c: "bg-violet-700 text-white", tags: ["steady", "observer"] },
      { t: "牌桌核數師", q: "你哋唔使計喇，最後pay曬我就得。", c: "bg-cyan-700 text-white", tags: ["observer", "shark"] },
      { t: "清袋總司令", q: "今晚任務好簡單，就係逐個逐個清袋。", c: "bg-rose-600 text-white", tags: ["hot", "shark"] },
      { t: "雀王本王", q: "唔使介紹，我個名就已經係戰績。", c: "bg-amber-600 text-white", tags: ["steady", "hot"] },
      { t: "收皮警告員", q: "你再出多兩隻，我真係會收晒你皮。", c: "bg-fuchsia-700 text-white", tags: ["explosive", "shark"] }
    ],
    WINNER: [
      { t: "截胡專家", q: "想食大牌？問過我先啦，我就係鍾意截你胡。", c: "bg-emerald-100 text-emerald-700", tags: ["shark", "observer"] },
      { t: "碰碰車神", q: "碰！碰！碰！碰多兩下你就清袋㗎喇。", c: "bg-blue-100 text-blue-700", tags: ["explosive", "chaos"] },
      { t: "連莊霸主", q: "坐得呢個位就唔打算起身，冧莊冧到你驚。", c: "bg-teal-100 text-teal-700", tags: ["hot", "grinder"] },
      { t: "食糊機器", q: "贏錢只係其次，我最享受係推牌果下聲。", c: "bg-green-100 text-green-700", tags: ["steady", "grinder"] },
      { t: "牌桌獵人", q: "我已經盯住你隻生章好耐喇。", c: "bg-orange-100 text-orange-700", tags: ["observer", "shark"] },
      { t: "技術型雀友", q: "打牌要講科學，計算先係王道。", c: "bg-blue-50 text-blue-600", tags: ["steady", "observer"] },
      { t: "收割機", q: "鋤強扶弱我就唔識，我淨係識收割。", c: "bg-emerald-600 text-white", tags: ["hot", "shark"] },
      { t: "食腦玩家", q: "你打運，我打命，你點同我鬥？", c: "bg-lime-600 text-white", tags: ["observer", "steady"] },
      { t: "截牌老司機", q: "你想食嗰隻牌，一早喺我對手入面。", c: "bg-cyan-600 text-white", tags: ["observer", "grinder"] },
      { t: "單吊之鬼", q: "單吊至係男人的浪漫，你識咩呀？", c: "bg-indigo-600 text-white", tags: ["explosive", "hot"] },
      { t: "默默食糊王", q: "我唔多說話，但我會默默收錢。", c: "bg-sky-100 text-sky-700", tags: ["steady", "observer"] },
      { t: "逆轉達人", q: "前面輸少少無所謂，尾段先係我表演時間。", c: "bg-amber-100 text-amber-700", tags: ["hot", "chaos"] },
      { t: "穩定收數姐", q: "唔使急，今晚大家慢慢畀返我就得。", c: "bg-emerald-50 text-emerald-800", tags: ["steady", "grinder"] },
      { t: "上分專員", q: "我唔急，反正最後都會慢慢上返去。", c: "bg-blue-100 text-blue-800", tags: ["grinder", "steady"] },
      { t: "開牌有料到", q: "一開牌我就知今晚邊個要埋單。", c: "bg-orange-100 text-orange-800", tags: ["observer", "hot"] },
      { t: "食住上玩家", q: "你一鬆手，我就順勢踩上去。", c: "bg-lime-100 text-lime-800", tags: ["hot", "shark"] }
    ],
    NORMAL: [
      { t: "資深雀骨", q: "摸多隻，等埋呢隻，我就自摸㗎喇。", c: "bg-slate-100 text-slate-600", tags: ["grinder", "steady"] },
      { t: "穩陣派宗師", q: "唔求贏大錢，最緊要唔好輸大牌。", c: "bg-gray-100 text-gray-700", tags: ["steady", "observer"] },
      { t: "摸牌達人", q: "呢隻牌，一摸落手就知係我想要個隻。", c: "bg-cyan-100 text-cyan-700", tags: ["hot", "explosive"] },
      { t: "隱世雀傑", q: "平時唔出聲，一出手就嚇死你。", c: "bg-zinc-100 text-zinc-700", tags: ["observer", "steady"] },
      { t: "雀壇中堅", q: "有我喺度，個場就唔會悶。", c: "bg-sky-50 text-sky-600", tags: ["grinder", "chaos"] },
      { t: "快手雀友", q: "打快啲啦，諗咁耐個發財都唔會變白板。", c: "bg-lime-100 text-lime-700", tags: ["chaos", "hot"] },
      { t: "太極高手", q: "以柔制剛，輸贏都係幾草嘢。", c: "bg-stone-100 text-stone-600", tags: ["steady", "observer"] },
      { t: "守門員", q: "我坐喺呢個位，就係要守住大家份糧。", c: "bg-neutral-200 text-neutral-700", tags: ["steady", "grinder"] },
      { t: "牌桌佛系男", q: "不求食糊，不求自摸，緣份到自然會贏。", c: "bg-orange-50 text-orange-700", tags: ["steady", "rookie"] },
      { t: "觀察家", q: "我睇穿晒你哋啲牌，不過我唔講。", c: "bg-slate-200 text-slate-800", tags: ["observer", "steady"] },
      { t: "跟章高手", q: "你出乜我未必食，但我一定知你想做乜。", c: "bg-emerald-50 text-emerald-700", tags: ["observer", "grinder"] },
      { t: "平衡型選手", q: "贏一鋪輸一鋪，最緊要個勢平均。", c: "bg-blue-50 text-blue-700", tags: ["steady", "chaos"] },
      { t: "有來有往哥", q: "你敬我一局，我回你一局，公平。", c: "bg-teal-50 text-teal-700", tags: ["steady", "grinder"] },
      { t: "控場主任", q: "我未必最勁，但個場一定唔會冷。", c: "bg-sky-100 text-sky-800", tags: ["chaos", "grinder"] },
      { t: "唔上唔落王", q: "輸又未到底，贏又未上天，啱啱好。", c: "bg-stone-50 text-stone-700", tags: ["steady", "observer"] },
      { t: "穩守突擊手", q: "平時守，啱位先一刀插落去。", c: "bg-emerald-100 text-emerald-800", tags: ["observer", "explosive"] }
    ],
    LOSER: [
      { t: "慈善大翁", q: "輸錢皆因贏錢起，我只係暫時將啲錢放喺你度。", c: "bg-rose-100 text-rose-700", tags: ["steady", "grinder"] },
      { t: "交學費大師", q: "我係嚟交學費嘅，各位前輩手下留情呀。", c: "bg-red-50 text-red-600", tags: ["rookie", "observer"] },
      { t: "外賣專員", q: "大家開開心心打牌，最緊要宵夜好食。", c: "bg-pink-100 text-pink-700", tags: ["chaos", "grinder"] },
      { t: "地獄黑仔王", q: "摸親都唔入，打親都出銃，天理何在？", c: "bg-stone-200 text-stone-700", tags: ["chaos", "explosive"] },
      { t: "積極參與者", q: "贏輸唔重要，最緊要有得打。", c: "bg-orange-50 text-orange-600", tags: ["grinder", "steady"] },
      { t: "散財童子", q: "今日我請，大家隨便食，隨便贏。", c: "bg-red-100 text-red-800", tags: ["chaos", "hot"] },
      { t: "人肉提款機", q: "密碼係 1234，大家隨便撳。", c: "bg-blue-200 text-blue-900", tags: ["grinder", "chaos"] },
      { t: "氣氛組組長", q: "雖然我輸錢，但係我講笑話好笑呀！", c: "bg-yellow-100 text-yellow-800", tags: ["chaos", "grinder"] },
      { t: "最後的溫柔", q: "我就係專登出銃畀你，費事你冇錢返屋企。", c: "bg-pink-50 text-pink-600", tags: ["steady", "rookie"] },
      { t: "逆風勇者", q: "今日風向唔啱，但我仲未認輸。", c: "bg-purple-50 text-purple-700", tags: ["grinder", "observer"] },
      { t: "倒水擔當", q: "我而家最叻唔係食糊，係幫大家加滿茶。", c: "bg-cyan-50 text-cyan-700", tags: ["rookie", "steady"] },
      { t: "牌運受害者", q: "我覺得自己技術冇問題，只係個天針對我。", c: "bg-slate-100 text-slate-700", tags: ["observer", "chaos"] },
      { t: "今晚又課金", q: "輸少當交月費，輸多當支持平台。", c: "bg-rose-50 text-rose-800", tags: ["grinder", "chaos"] },
      { t: "被胡之神", q: "你哋一叫糊，我個心就知又關我事。", c: "bg-amber-50 text-amber-800", tags: ["chaos", "observer"] },
      { t: "爛尾工程師", q: "鋪鋪都好似差一隻，真係差到喊。", c: "bg-blue-50 text-blue-800", tags: ["steady", "observer"] }
    ],
    NOOB: [
      { t: "雀壇新丁", q: "邊隻係一筒話？我仲分唔清。", c: "bg-slate-50 text-slate-400", tags: ["rookie", "observer"] },
      { t: "觀察員", q: "我睇多兩鋪先，你哋打先啦。", c: "bg-stone-50 text-stone-400", tags: ["observer", "rookie"] },
      { t: "潛力股", q: "等我學成歸來，實贏返晒你哋。", c: "bg-violet-50 text-violet-500", tags: ["hot", "rookie"] },
      { t: "幸運小草", q: "亂打亂撞，竟然比我食到個亂碟。", c: "bg-green-50 text-green-500", tags: ["chaos", "rookie"] },
      { t: "熱情新手", q: "再黎一局！我開始掌握到規律喇。", c: "bg-amber-50 text-amber-500", tags: ["grinder", "rookie"] },
      { t: "陪跑專員", q: "我今日嚟主要係負責洗牌同埋畀錢。", c: "bg-gray-50 text-gray-400", tags: ["rookie", "steady"] },
      { t: "路過英雄", q: "我只係路過，點知畀你哋拉咗入嚟打。", c: "bg-zinc-100 text-zinc-500", tags: ["rookie", "chaos"] },
      { t: "學徒", q: "師父話齋，未贏錢先要學識輸錢。", c: "bg-emerald-50 text-emerald-500", tags: ["rookie", "observer"] },
      { t: "實習雀友", q: "實習期內，請大家多多指教。", c: "bg-blue-50 text-blue-400", tags: ["rookie", "grinder"] },
      { t: "純情小白兔", q: "你哋啲牌咁複雜，我睇唔透呀。", c: "bg-rose-50 text-rose-400", tags: ["rookie", "observer"] },
      { t: "摸索中玩家", q: "而家最重要唔係贏，係記得邊隻牌唔好出。", c: "bg-lime-50 text-lime-600", tags: ["rookie", "steady"] },
      { t: "起步線冠軍", q: "雖然而家未贏，但我個心態贏咗。", c: "bg-sky-50 text-sky-500", tags: ["rookie", "hot"] },
      { t: "新手保護期", q: "你哋唔好咁狠，我仲喺新手教學入面。", c: "bg-fuchsia-50 text-fuchsia-600", tags: ["rookie", "observer"] },
      { t: "跟打見習生", q: "我而家最叻就係跟住隔籬位打。", c: "bg-teal-50 text-teal-600", tags: ["rookie", "steady"] },
      { t: "試牌學徒", q: "今鋪試下咁打，唔得下鋪再算。", c: "bg-orange-50 text-orange-600", tags: ["rookie", "chaos"] },
      { t: "出銃體驗員", q: "每一隻錯牌，都係成長嘅印記。", c: "bg-red-50 text-red-500", tags: ["rookie", "hot"] }
    ]
  }
};
